/** ADR-06: inspect foreign Markdown in place; explicit field/value decisions and staged upgrades. */
import {parseDocument,patchHead,listValue} from './core/document.mjs';
import {readRegister} from './core/ontology.mjs';
import {relativePath,requireThat,nonempty} from './core/errors.mjs';
import {visibleKnowledge,STATUS_VALUES} from './content.mjs';
import {proposal,prepareChanges,operateChanges} from './change-set.mjs';
export const coreFields=new Set('id type status title description class owner related readers language aliases tags generated sources verified stale_after postponed_until postponed_reason resource source_id extraction superseded_by source_created_at source_modified_at generated_at contribute_to shared_copy'.split(' '));
export const fieldFile='schema/FIELDS.json';
export async function readFields(store){const file=await store.read(fieldFile);const data=file?JSON.parse(file.text):{format:'llmwiki-fields/1',fields:[]};requireThat(data.format==='llmwiki-fields/1'&&Array.isArray(data.fields)&&data.fields.every(f=>typeof f.name==='string')&&new Set(data.fields.map(f=>f.name)).size===data.fields.length,'fields','Invalid field register.');return {file,data};}
const eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
export async function assessCollection(store,{folder='',readers=[]}={}){
 relativePath(folder,{root:true});const fields=new Map(),pages=[],findings=[],ids=new Map(),names=new Map();let register=null;const registered=await store.read('schema/TYPES.md');
 try{if(registered)register=readRegister(registered.text);}catch(e){findings.push({page:'schema/TYPES.md',code:e.code??'ontology',message:e.message});}
 let extensions=[];try{extensions=(await readFields(store)).data.fields;}catch(e){findings.push({page:fieldFile,code:'fields',message:e.message});}
 async function visit(dir){let entries;try{entries=await store.list(dir,{recursive:false});}catch(e){findings.push({page:dir,code:e.code??'read',message:e.message});return;}
  for(const entry of entries){if(entry.kind==='directory'){await visit(entry.path);continue;}if(entry.kind!=='file'||!visibleKnowledge(entry.path))continue;
   try{const file=await store.read(entry.path);requireThat(file,'missing','File disappeared during assessment.');const parsed=parseDocument(file.text),head=parsed.visibleHead??parsed.head;pages.push({page:entry.path,expected:file.sha256,fields:Object.keys(head),readers});
    for(const [field,value]of Object.entries(head)){if(!fields.has(field))fields.set(field,{field,known:coreFields.has(field)||extensions.some(f=>f.name===field),values:[]});const row=fields.get(field);for(const item of Array.isArray(value)?value:[value]){let v=row.values.find(v=>eq(v.value,item));if(!v){const allowed=field==='type'?[...register?.genera.keys()??[]]:field==='status'?STATUS_VALUES:field==='class'?[...new Set([...register?.genera.values()??[]].flatMap(g=>g.classes))]:extensions.find(f=>f.name===field)?.values;v={value:item,count:0,registered:allowed?allowed.some(a=>eq(a,item)):row.known};row.values.push(v);}v.count++;}}
    if(head.id){const key=String(head.id);ids.set(key,[...ids.get(key)??[],entry.path]);}const name=entry.path.split('/').at(-1);names.set(name,[...names.get(name)??[],entry.path]);
   }catch(e){pages.push({page:entry.path,error:{code:e.code??'read',message:e.message}});findings.push({page:entry.path,code:e.code??'read',message:e.message});}
  }
 }
 await visit(folder);for(const [id,paths]of ids)if(paths.length>1)findings.push({code:'duplicate_id',id,pages:paths});for(const [name,paths]of names)if(paths.length>1)findings.push({code:'ambiguous_name',name,pages:paths});
 const result={folder,readers,pages,fields:[...fields.values()].sort((a,b)=>a.field.localeCompare(b.field)),findings,register_expected:registered?.sha256??null,complete:!findings.length,read_only:true};return {...result,token:await store.services.hash(JSON.stringify(result))};
}
export function inFolder(page,folder){return visibleKnowledge(page)&&(!folder||page.startsWith(folder+'/'));}
async function checkDependencies(store,data){for(const d of data.dependencies){const f=await store.read(d.page);requireThat((f?.sha256??null)===d.expected,'stale','A preview dependency changed.',{page:d.page});}}
export async function collectionUpgrade(store,args){
 const {step='preview',folder='',changes,author,stage}=args;if(!['preview','prepare'].includes(step))return operateChanges(store,args,'upgrade',{check:d=>checkDependencies(store,d)});
 relativePath(folder,{root:true});requireThat(Array.isArray(changes)&&changes.length,'changes','Choose a nonempty stage.');for(const c of changes){requireThat(inFolder(c.page,folder),'scope','A stage changes only Markdown within its chosen folder.');const prior=await store.read(c.page),before=prior?parseDocument(prior.text):null,after=parseDocument(c.text);for(const key of ['id','resource','extraction','source_id','sources','generated'])requireThat(eq(before?.head[key],after.head[key]),'protected','Upgrade stages preserve identity and provenance.');requireThat(!before?.head.resource||before.body===after.body,'source_ingest_required','Source mirrors are changed only through source.ingest.');}
 const preview=await proposal(store,{kind:'upgrade',folder,label:stage,author,changes});return step==='prepare'?prepareChanges(store,preview,args.expected):preview;
}
function comments(node,result=[]){if(!node||typeof node!=='object')return result;for(const key of ['commentBefore','comment'])if(node[key])result.push(node[key]);for(const item of node.items??[])comments(item,result);comments(node.contents,result);comments(node.key,result);comments(node.value,result);return result;}
function retainComments(before,after){const old=comments(parseDocument(before).yaml),remaining=comments(parseDocument(after).yaml),missing=[];for(const comment of old){const at=remaining.indexOf(comment);if(at>=0)remaining.splice(at,1);else missing.push(comment);}if(!missing.length)return after;const p=parseDocument(after);return p.prefix+missing.flatMap(c=>c.split('\n').map(line=>'#'+line+'\n')).join('')+after.slice(p.prefix.length);}
function renameField(text,from,to){if(from===to)return text;const p=parseDocument(text),pair=p.yaml?.contents.items.find(row=>row.key?.value===from);requireThat(pair,'mapping','The mapped field disappeared.');requireThat(!Object.hasOwn(p.visibleHead??p.head,to),'mapping','Two fields would overwrite the same meaning.',{field:from,target:to});const start=p.prefix.length+pair.key.range[0],end=p.prefix.length+pair.key.range[1];return text.slice(0,start)+to+text.slice(end);}
export async function mapCollection(store,args){
 const {step='preview',folder='',mappings,author}=args;if(!['preview','prepare'].includes(step))return operateChanges(store,args,'mapping',{check:d=>checkDependencies(store,d)});
 const report=await assessCollection(store,{folder});requireThat(report.complete,'assessment','Resolve unreadable or ambiguous files before mapping.',{findings:report.findings});requireThat(Array.isArray(mappings)&&mappings.length===report.fields.length&&new Set(mappings.map(m=>m.field)).size===mappings.length&&report.fields.every(f=>mappings.some(m=>m.field===f.field)),'mapping','Decide every observed field, including explicit keep decisions.',{fields:report.fields});
 const registered=await store.read('schema/TYPES.md');requireThat(registered,'ontology','Initialize a type register before mapping.');const register=readRegister(registered.text),{file:fieldRecord,data:fields}=await readFields(store),changes=[],inherited=new Set();
 for(const row of report.fields){const m=mappings.find(m=>m.field===row.field);requireThat(m.to==='keep'||/^[a-z][a-z0-9_]*$/.test(m.to)&&!Object.hasOwn(Object.prototype,m.to)&&m.to!=='prototype','mapping','Choose a valid target field or keep.');
  if(m.to==='keep')continue;requireThat(!['id','resource','generated','sources','extraction','source_id'].includes(row.field)&&!['id','resource','generated','sources','extraction','source_id'].includes(m.to),'mapping','Identity and technical provenance cannot be remapped.');requireThat(coreFields.has(m.to)||fields.fields.some(f=>f.name===m.to),'mapping','Register an extension field before using it.');requireThat(Array.isArray(m.values)&&row.values.every(v=>m.values.filter(x=>eq(x.from,v.value)).length===1),'mapping','Decide every observed value; unknown meanings are never guessed.',{field:row.field});
  for(const v of m.values){if(m.to==='type'&&!register.genera.has(v.to)){requireThat(m.inherit===true&&v.to===v.from&&/^[a-z][a-z0-9_-]*$/.test(v.to),'mapping','Choose a registered type or explicitly retain an inherited type.');inherited.add(v.to);}if(m.to==='status')requireThat(STATUS_VALUES.includes(v.to),'mapping','Choose a registered status.');if(m.to==='class')requireThat([...register.genera.values()].some(g=>g.classes.includes(v.to)),'mapping','Choose a registered class.');}
 }
 for(const page of report.pages){const file=await store.read(page.page);requireThat(file.sha256===page.expected,'stale','The collection changed.');let text=file.text;const head=parseDocument(text).visibleHead??parseDocument(text).head;
  for(const m of mappings){if(m.to==='keep'||!Object.hasOwn(head,m.field))continue;const map=value=>m.values.find(v=>eq(v.from,value)).to;let next=Array.isArray(head[m.field])?head[m.field].map(map):map(head[m.field]);if(['type','status','class'].includes(m.to)){if(Array.isArray(next)){requireThat(Object.hasOwn(m,'value')&&next.includes(m.value),'mapping','Resolve multiple meanings with one explicit value from the mapped choices.',{page:page.page,field:m.field,choices:next});next=m.value;}requireThat(typeof next==='string','mapping','A type, class or status is one registered value.');}text=renameField(text,m.field,m.to);if(!eq(head[m.field],next))text=patchHead(text,{[m.to]:next});}
  text=retainComments(file.text,text);const resulting=parseDocument(text).head;if(mappings.some(m=>m.to==='class')&&resulting.class&&register.genera.has(resulting.type))requireThat(register.genera.get(resulting.type).classes.includes(resulting.class),'mapping','The selected class does not belong to the selected type.',{page:page.page});changes.push({page:page.page,expected:file.sha256,text});
 }
 if(inherited.size){let text=registered.text;const entries=[...inherited].map((name,i)=>'### '+name+'\n\n- Label: '+name+'\n- Question: \n- Order: '+(Math.max(...[...register.genera.values()].map(g=>g.order))+i+1)+'\n- Classes: \n- Required from stable: \n- Sections: \n- Edges out: \n- Related required: false\n- Stale interval: null\n- Origin: inherited\n\n').join('');text=text.replace('## Edges',entries+'## Edges');readRegister(text);changes.unshift({page:'schema/TYPES.md',expected:registered.sha256,text});}
 const dependencies=[{page:fieldFile,expected:fieldRecord?.sha256??null},...(inherited.size?[]:[{page:'schema/TYPES.md',expected:registered.sha256}])];
 const preview=await proposal(store,{kind:'mapping',folder,label:'Vocabulary mapping',author,changes,dependencies,details:{mappings,fields:report.fields,adopted_pages:report.pages.map(p=>({page:p.page,expected:p.expected}))}});return step==='prepare'?prepareChanges(store,preview,args.expected):preview;
}
