/** FIX-02-05-01: actual chat uptake before original storage; no inferred consent. */
import {requireThat,nonempty,relativePath} from './core/errors.mjs';
import {parseDocument} from './core/document.mjs';
const ROOT='.llmwiki/intakes';
const location=id=>{requireThat(typeof id==='string'&&/^[a-f0-9]{32}$/.test(id),'intake_required','Start the guided intake and record the actual uptake decision first.');return ROOT+'/'+id+'.json';};
export async function intakeStatus(store,id){const file=await store.read(location(id));requireThat(file,'intake_required','The uptake record is missing.');const data=JSON.parse(file.text);requireThat(data.format==='llmwiki-intake/1','intake_required','Unknown uptake record.');return data;}
export async function startIntake(store,args,source){
 const {path,sha256,assessment,compared,topics,author}=args;relativePath(path);requireThat(/^[a-f0-9]{64}$/.test(sha256),'digest','Read the original attachment first.');nonempty(author,'author');nonempty(assessment,'comparison with existing knowledge');requireThat(Array.isArray(compared)&&Array.isArray(topics)&&topics.length,'triage','Record compared knowledge and candidate themes.');
 for(const c of compared){const f=await store.read(relativePath(c.page));nonempty(c.quote,'comparison quote');nonempty(c.reason,'comparison reason');requireThat(f&&f.sha256===c.expected&&parseDocument(f.text).body.includes(c.quote),'evidence','Read and quote the actual compared note.');}
 for(const t of topics){nonempty(t.title,'theme');nonempty(t.reason,'theme reason');}
 const data={format:'llmwiki-intake/1',id:store.services.uuid().replace(/-/g,''),source,path,sha256,assessment,compared,topics,author,at:store.services.now(),decision:null,decisions:[]};await store.write(location(data.id),JSON.stringify(data,null,2)+'\n',{expected:null});return data;
}
export async function decideIntake(store,args){const file=await store.read(location(args.id));requireThat(file,'intake_required','The uptake record is missing.');const data=JSON.parse(file.text),d=args.decision;requireThat(data.format==='llmwiki-intake/1','intake_required','Unknown uptake record.');nonempty(args.author,'responding author');nonempty(d?.reply,'actual user reply');requireThat(['take','defer','decline'].includes(d.choice),'decision','Choose take, defer or decline.');
 if(d.choice==='take'){requireThat(Array.isArray(d.selected)&&d.selected.length&&new Set(d.selected).size===d.selected.length&&d.selected.every(i=>Number.isInteger(i)&&i>=1&&i<=data.topics.length),'topics','Record the themes selected by the user.');requireThat(['elaboration','entries','existing','source-only'].includes(d.form),'form','Record the agreed result form.');}
 for(const c of data.compared)requireThat((await store.read(c.page))?.sha256===c.expected,'stale','Compared knowledge changed; repeat the triage.');
 data.decisions??=data.decision?[data.decision]:[];data.decision={...d,author:args.author,at:store.services.now()};data.decisions.push(data.decision);await store.write(location(data.id),JSON.stringify(data,null,2)+'\n',{expected:file.sha256});return data;
}
export async function authorizeIntake(store,id,source,path,bytes){const data=await intakeStatus(store,id);requireThat(data.source===source&&data.path===path&&data.sha256===await store.services.hash(bytes),'intake_required','The confirmed attachment or target differs. Repeat the triage for this target.');requireThat(data.decision?.choice==='take','intake_required','Wait for the actual uptake decision before storing the original.');return data;}
export async function requireDialogMode(store,sources,mode){let files;try{files=await store.list(ROOT);}catch(e){if(e.code==='ENOENT')return;throw e;}for(const page of sources){const head=parseDocument((await store.read(page)).text).head;for(const file of files.filter(e=>e.kind==='file'&&e.path.endsWith('.json'))){const intake=JSON.parse((await store.read(file.path)).text);if(intake.source===head.resource?.store&&intake.path===head.resource?.name&&intake.sha256===head.resource?.sha256&&intake.decision?.choice==='take')requireThat(mode==='appropriate','dialogue_required','A chat attachment uses its confirmed appropriation dialogue, not automatic batch integration.');}}}
