/** ADR-06: adopt explicit MkDocs navigation in place without moving pages or site files. */
import {parseDocument as parseYAML} from 'yaml';
import {relativePath,requireThat} from './core/errors.mjs';
import {patchHead,parseDocument} from './core/document.mjs';
import {proposal,prepareChanges,operateChanges} from './change-set.mjs';
import {readFields,fieldFile,inFolder} from './collection.mjs';
export async function adoptPublished(store,args){
 const {step='preview',navigation,author}=args;
 if(!['preview','prepare','check'].includes(step))return operateChanges(store,args,'published',{check:async data=>{for(const dep of data.dependencies)requireThat((await store.read(dep.page))?.sha256===dep.expected,'stale','Publication navigation changed.');}});
 relativePath(navigation);const config=await store.read(navigation);requireThat(config,'navigation','Choose the existing navigation configuration.');const parsed=parseYAML(config.text,{uniqueKeys:true});requireThat(!parsed.errors.length,'navigation','Navigation YAML is invalid.');const nav=parsed.toJS({maxAliasCount:50});requireThat(Array.isArray(nav?.nav),'navigation','Provide a MkDocs configuration with an explicit nav list; groups are never inferred.');
 const parent=navigation.split('/').slice(0,-1).join('/'),docs=nav.docs_dir??'docs';const clean=relativePath(docs,{root:true});const folder=[parent,clean].filter(Boolean).join('/'),rows=[],seen=new Set();
 function walk(items,groups=[]){requireThat(Array.isArray(items),'navigation','Navigation groups must contain lists.');for(const item of items){if(typeof item==='string'){add(item,groups);continue;}requireThat(item&&typeof item==='object'&&!Array.isArray(item)&&Object.keys(item).length===1,'navigation','Each navigation entry has one label.');const [label,value]=Object.entries(item)[0];if(Array.isArray(value))walk(value,[...groups,label]);else add(value,groups);}}
 function add(value,groups){requireThat(typeof value==='string','navigation','A navigation target must be a file or URL.');if(/^https?:\/\//.test(value))return;const page=[folder,value.split('#')[0]].filter(Boolean).join('/');relativePath(page);requireThat(inFolder(page,folder)&&!seen.has(page),'navigation','Only unique existing Markdown pages can be adopted.');seen.add(page);rows.push({page,groups,order:rows.length});}
 walk(nav.nav);requireThat(rows.length,'navigation','No local Markdown entries are present.');const unlisted=(await store.list(folder)).filter(e=>e.kind==='file'&&inFolder(e.path,folder)&&!seen.has(e.path)).map(e=>e.path),findings=[],changes=[];for(const row of rows){const file=await store.read(row.page);if(!file){findings.push({code:'publication_missing',page:row.page});continue;}const head=parseDocument(file.text).head;if(step==='check'&&!Object.hasOwn(head,'publication_group'))findings.push({code:'publication_not_adopted',page:row.page});if(Object.hasOwn(head,'publication_group')&&(JSON.stringify(head.publication_group)!==JSON.stringify(row.groups)||head.publication_order!==row.order))findings.push({code:'publication_drift',page:row.page,document:{groups:head.publication_group,order:head.publication_order},navigation:{groups:row.groups,order:row.order},authority:'document'});changes.push({page:row.page,expected:file.sha256,text:patchHead(file.text,{publication_group:row.groups,publication_order:row.order})});}
 if(step==='check')return {navigation,pages:rows,unlisted,findings,complete:!findings.length,read_only:true};requireThat(!findings.length,'publication_drift','Document fields are authoritative after adoption. Reconcile the navigation with them.',{findings});
 const {file,data}=await readFields(store);for(const field of [{name:'publication_group',type:'list',kind:'publication'},{name:'publication_order',type:'number',kind:'publication'}]){const old=data.fields.find(f=>f.name===field.name);requireThat(!old||old.kind===field.kind&&old.type===field.type,'fields','A publication field has a conflicting definition.');if(!old)data.fields.push(field);}
 changes.unshift({page:fieldFile,expected:file?.sha256??null,text:JSON.stringify(data,null,2)+'\n'});
 const preview=await proposal(store,{kind:'published',folder,label:'Adopt published structure',author,changes,dependencies:[{page:navigation,expected:config.sha256}],details:{navigation,pages:rows,unlisted,publication_unchanged:true,links:'Existing paths and Markdown body bytes are retained.'}});return step==='prepare'?prepareChanges(store,preview,args.expected):preview;
}
