/* Build-time only: node scripts/build_office.mjs /path/to/esbuild/lib/main.js
   User machines run only the generated self-contained browser payload. */
import {readFile,writeFile} from 'node:fs/promises';
import {resolve,relative} from 'node:path';
import {gzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
const {build,version}=await import(pathToFileURL(resolve(process.argv[2])).href);
const result=await build({entryPoints:['scripts/office/runtime.js'],bundle:true,write:false,format:'iife',target:'es2022',define:{'import.meta.url':'"file:///bundled/"'},minify:true,legalComments:'inline',metafile:true,loader:{'.wasm':'base64'},plugins:[{name:'local-ooxml',setup(b){
// Upstream parser workers are self-contained. Classic Blob workers also work
// in opaque-origin frames; module workers fail their origin check there.
b.onLoad({filter:/[\/]ooxml[\/]dist[\/](docx|xlsx|pptx)-[^/]+\.js$/},async args=>({contents:(await readFile(args.path,'utf8')).replaceAll('"URL.revokeObjectURL(import.meta.url);",','').replaceAll('type: "module"','type: "classic"'),loader:'js'}));
b.onResolve({filter:/^@silurus\/ooxml\//},args=>({path:resolve('vendor/office/ooxml/dist/'+args.path.split('/').pop()+'.mjs')}));}}]});
const css=await readFile('vendor/office/zrimo/dist/styles.css','utf8');
const extra=`.office-fallback-hint{font:13px system-ui;padding:12px;border-bottom:1px solid #ddd;color:#666}.office-fallback-text{font:15px/1.6 system-ui;white-space:pre-wrap;overflow:auto;height:calc(100% - 70px);padding:0 24px} #office .zrimo-ui__button{border-color:transparent;min-width:28px;height:28px;padding:0 6px;background:transparent} html,body,#office{margin:0;width:100%;height:100%;overflow:hidden} #office .zrimo-ui{--zrimo-background:#ededed;--zrimo-surface:#fafafa;--zrimo-text:#303030;--zrimo-muted:#666;--zrimo-border:#ddd;--zrimo-primary:#626262;--zrimo-radius:3px;--zrimo-toolbar-height:38px} button[data-action=download]{display:none} button svg{width:16px;height:16px;vertical-align:middle} @media(prefers-color-scheme:dark){#office .zrimo-ui{--zrimo-background:#262626;--zrimo-surface:#222;--zrimo-text:#ddd;--zrimo-muted:#aaa;--zrimo-border:#383838;--zrimo-primary:#bcbcbc;--zrimo-primary-contrast:#222}}`;
const policy="default-src 'none'; script-src 'unsafe-inline' 'wasm-unsafe-eval'; style-src 'unsafe-inline'; img-src blob: data:; font-src blob: data:; worker-src blob:; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'";
const noticeFiles=['vendor/office/ooxml/LICENSE','vendor/office/ooxml/THIRD_PARTY_NOTICES.md','vendor/office/zrimo/LICENSE-MIT','vendor/office/zrimo/LICENSE-APACHE','vendor/office/zrimo/THIRD_PARTY_NOTICES.md'];
const notices='Bundled Office viewer: @silurus/ooxml 0.72.2, @zrimo/viewer 0.1.2.\nOnly Office runtime assets are included; PDF.js, Noto fonts, image/TIFF and MathJax assets mentioned in upstream notices are excluded.\nParser worker packaging adapted to classic Blob workers for opaque-origin frames.\n\n'+(await Promise.all(noticeFiles.map(async name=>'SOURCE: '+name+'\n'+await readFile(name,'utf8')))).join('\n\n');
await writeFile('runtime/assets/office-NOTICES.txt',notices);
const html='<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="'+policy+'"><style>'+css+extra+'</style></head><body><div id="office"></div><script>'+result.outputFiles[0].text.replace(/<\/script/gi,'<\\/script')+'</script><!--'+notices.replaceAll('--','- -')+'--></body></html>';
const packed=gzipSync(Buffer.from(html),{level:9}).toString('base64');
const output='/* Generated by scripts/build_office.mjs from pinned local vendors.\n   Compressed HTML includes the renderer, WASM, CSS and notices; it runs only\n   in a sandboxed frame with network access disabled. See office-NOTICES.txt. */\n(function(g){"use strict";let document;g.OfficeBundle={html:async function(){if(!document)document=(async()=>{const bytes=Uint8Array.from(atob("'+packed+'"),c=>c.charCodeAt(0));return new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"))).text();})();return document;}};})(globalThis);\n';
await writeFile('app/officebundle.js',output);
const inputs={};for(const name of Object.keys(result.metafile.inputs).sort())inputs[name]=createHash('sha256').update(await readFile(name)).digest('hex');
for(const name of ['scripts/build_office.mjs','vendor/office/ooxml/package.json','vendor/office/zrimo/package.json',...noticeFiles])inputs[name]=createHash('sha256').update(await readFile(name)).digest('hex');
inputs['vendor/office/zrimo/dist/styles.css']=createHash('sha256').update(css).digest('hex');
await writeFile('vendor/office/manifest.json',JSON.stringify({builder:{esbuild:version},packages:{'@silurus/ooxml':'0.72.2','@zrimo/viewer':'0.1.2'},inputs,output:{file:'app/officebundle.js',sha256:createHash('sha256').update(output).digest('hex'),bytes:Buffer.byteLength(output)}},null,2)+'\n');
console.log(JSON.stringify({htmlBytes:html.length,packedBytes:output.length,inputs:Object.keys(inputs).length}));
