/** Native browser folder handles implement the same text store used by the wiki core. */
import {relativePath,requireThat} from '../core/errors.mjs';
export function browserStore(dir,files,reviews){
 const services={now:()=>new Date().toISOString(),uuid:()=>crypto.randomUUID(),random:size=>crypto.getRandomValues(new Uint8Array(size)),hash:async value=>typeof value==='string'?reviews.hash(value):Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',value)),b=>b.toString(16).padStart(2,'0')).join('')};
 const store={services,async mkdir(path){relativePath(path);let handle=dir;for(const part of path.split('/'))handle=await handle.getDirectoryHandle(part,{create:true});},
 async archive(from,to,expected){const seen=await store.read(from);requireThat(seen?.sha256===expected,'stale','The original changed before archiving.');requireThat(!await store.read(to),'exists','Archive destination exists.');await store.write(to,seen.text,{expected:null});requireThat((await store.read(from))?.sha256===expected,'stale','The original changed; both copies are retained.');let handle=dir;const parts=from.split('/');for(const part of parts.slice(0,-1))handle=await handle.getDirectoryHandle(part);await handle.removeEntry(parts.at(-1));},async read(page,{binary=false}={}){relativePath(page);if(binary){try{return {...await files.readBinary(dir,page),path:page};}catch(error){if(error.name==='NotFoundError')return null;throw error;}}const value=await files.peek(dir,page);if(!value)return null;requireThat(typeof value.text==='string','permission','Read permission is missing.');return {...value,path:page,sha256:await services.hash(value.text),size:new TextEncoder().encode(value.text).length};},
 async write(page,text,{expected}={}){if(text instanceof Uint8Array){const before=await store.read(page,{binary:true});requireThat((before?.sha256??null)===expected,'stale','The attachment changed.');const done=await files.writeBinary(dir,page,text,before);requireThat(done.saved,'stale','The attachment changed during saving.');return done;}const seen=await files.peek(dir,page);requireThat(!seen||typeof seen.text==='string','permission','Write permission is missing.');requireThat((seen?await services.hash(seen.text):null)===expected,'stale','The document changed.');const done=await files.writeFile(dir,page,text,seen);requireThat(done.saved,'stale','The document changed before it could be saved.');return {...done,sha256:await services.hash(text)};},
 async list(prefix='',{recursive=true,hidden=false}={}){let start=dir;for(const p of prefix.split('/').filter(Boolean))start=await start.getDirectoryHandle(p);const out=[];async function walk(folder,base){for await(const entry of folder.values()){const name=base?base+'/'+entry.name:entry.name;if(!hidden&&(entry.name.startsWith('.')||entry.name.startsWith('~$')))continue;out.push({path:name,kind:entry.kind});if(recursive&&entry.kind==='directory')await walk(entry,name);}}await walk(start,prefix);return out;}};
 return store;
}
